### ISSUE TITLE
Create release version 5.1.2

### ISSUE THREAD

**Issue by samtux** [rozos/TauDEM-QGIS#1]
Thanks for sharing your great work @rozos. I maintain the package of TauDEM  in Arch Linux [1]. However I would ask the possibility of create a release in GitHub  of TauDEM 5.1.2 so that you can access to versions offered.

Thank You,

Samuel Mesa.

[1] https://aur.archlinux.org/packages/taudem/

**Comment by rozos** [comment]
Dear Samuel,

I am not sure what you are asking me.

Regards

**Comment by samtux** [comment]
Sorry, I should have explained what I meant.  It is the possibility of creating a label with git or release of stable version of TauDEM-QGIS, ie 5.1.2. It is to preserve that future changes do not affect the packages we created from your code.

To create the release is via:

https://github.com/rozos/TauDEM-QGIS/releases

Thanks.

**Comment by rozos** [comment]
I think I have done it. Please check it out.

**Comment by samtux** [comment]
Thanks @rozos  and thanks again for sharing your work.
